apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portfolio-frontend
  name: portfolio-frontend
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: portfolio-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: portfolio-frontend
    spec:
      containers:
      - image: registry.comarlau.com/portfolio:latest
        imagePullPolicy: Always
        name: portfolio
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
